# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

name: R-CMD-check

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "BiocManager"))
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", build_args = "--no-build-vignettes")
        shell: Rscript {0}
        env:
          NOT_CRAN: TRUE
          _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
          _R_CHECK_CRAN_INCOMING_: FALSE
          _R_CHECK_FORCE_SUGGESTS_: FALSE
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        env:
          RSPM: https://packagemanager.rstudio.com/all/__linux__/bionic/latest
      - name: System dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev openjdk-11-jdk
          sudo R CMD javareconf
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "BiocManager"))
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", build_args = "--no-build-vignettes")
        shell: Rscript {0}
        env:
          NOT_CRAN: TRUE
          _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
          _R_CHECK_CRAN_INCOMING_: FALSE
          _R_CHECK_FORCE_SUGGESTS_: FALSE
